/* eslint-disable */
// AUTO-GENERATED by scripts/probe-codes.mjs from live TUNEPS detail payloads.
// Harvested 2026-07-25 over 600 recent notices.
// Re-run: node scripts/probe-codes.mjs 6 > _probe/reference.json

export const RAW_REFERENCE = {
  "gov": {
    "10": {
      "fr": "ZAGHOUAN",
      "ar": "زغوان"
    },
    "11": {
      "fr": "SOUSSE",
      "ar": "سوسة"
    },
    "12": {
      "fr": "MONASTIR",
      "ar": "المنستير"
    },
    "13": {
      "fr": "MAHDIA",
      "ar": "المهدية"
    },
    "14": {
      "fr": "KAIROUAN",
      "ar": "القيروان"
    },
    "15": {
      "fr": "KASSERINE",
      "ar": "القصرين"
    },
    "16": {
      "fr": "SIDI BOUZID",
      "ar": "سيدي بوزيد"
    },
    "17": {
      "fr": "SFAX",
      "ar": "صفاقس"
    },
    "18": {
      "fr": "GAFSA",
      "ar": "قفصة"
    },
    "19": {
      "fr": "TOZEUR",
      "ar": "توزر"
    },
    "20": {
      "fr": "GABES",
      "ar": "قابس"
    },
    "21": {
      "fr": "MEDENINE",
      "ar": "مدنين"
    },
    "22": {
      "fr": "TATAOUINE",
      "ar": "تطاوين"
    },
    "23": {
      "fr": "KEBILI",
      "ar": "قبلي"
    },
    "24": {
      "fr": "MANOUBA",
      "ar": "منوبة"
    },
    "99": {
      "fr": "Autres",
      "ar": "أخرى"
    },
    "01": {
      "fr": "TUNIS",
      "ar": "تونس"
    },
    "08": {
      "fr": "SILIANA",
      "ar": "سليانة"
    },
    "02": {
      "fr": "ARIANA",
      "ar": "أريانة"
    },
    "06": {
      "fr": "BEJA",
      "ar": "باجة"
    },
    "05": {
      "fr": "NABEUL",
      "ar": "نابل"
    },
    "03": {
      "fr": "BEN AROUS",
      "ar": "بن عروس"
    },
    "07": {
      "fr": "KEF",
      "ar": "الكاف"
    },
    "04": {
      "fr": "BIZERTE",
      "ar": "بنزرت"
    },
    "09": {
      "fr": "JENDOUBA",
      "ar": "جندوبة"
    }
  },
  "domain": {
    "2391": {
      "fr": "Fourniture de biens",
      "ar": "التزود بمواد"
    },
    "2392": {
      "fr": "Travaux",
      "ar": "أشغال"
    },
    "2393": {
      "fr": "Fourniture de services",
      "ar": "التزود بخدمات"
    },
    "2394": {
      "fr": "Etudes",
      "ar": "دراسات"
    }
  },
  "category": {
    "101": {
      "fr": "Fournitures des biens",
      "ar": "التزود بمواد"
    },
    "102": {
      "fr": "Fournitures de bureau",
      "ar": "مواد مكتبية"
    },
    "103": {
      "fr": "Habillement",
      "ar": "إكساء"
    },
    "104": {
      "fr": "Nourriture",
      "ar": "تغذية"
    },
    "105": {
      "fr": "Produits d’entretien",
      "ar": "مواد تنظيف"
    },
    "106": {
      "fr": "Fournitures agricoles",
      "ar": "مواد فلاحية"
    },
    "107": {
      "fr": "Consommables informatiques",
      "ar": "مواد إستهلاكية إعلامية"
    },
    "108": {
      "fr": "Matériaux de construction",
      "ar": "مواد بناء"
    },
    "109": {
      "fr": "Produits pharmaceutiques",
      "ar": "مواد صيدلية"
    },
    "110": {
      "fr": "Autres Fournitures",
      "ar": "معدات أخرى"
    },
    "111": {
      "fr": "Matériel",
      "ar": "مواد"
    },
    "114": {
      "fr": "Matériels scientifiques",
      "ar": "معدات علمية"
    },
    "115": {
      "fr": "Materiels informatiques",
      "ar": "معدات إعلامية"
    },
    "116": {
      "fr": "Equipements de télécommunication",
      "ar": "تجهيزات الربط والإتصال"
    },
    "117": {
      "fr": "Equipements électroniques",
      "ar": "تجهيزات الربط والإتصال"
    },
    "118": {
      "fr": "Equipements hydromécaniques",
      "ar": "تجهيزات هيدروميكانيكية"
    },
    "120": {
      "fr": "Matériel de bureau",
      "ar": "مواد مكتبية"
    },
    "121": {
      "fr": "Matériel medical",
      "ar": "معدات طبية"
    },
    "122": {
      "fr": "Matériel agricole",
      "ar": "معدات فلاحية"
    },
    "123": {
      "fr": "Matériels roulants",
      "ar": "معدات دارجة"
    },
    "124": {
      "fr": "Equipements électriques",
      "ar": "معدات كهربائية"
    },
    "125": {
      "fr": "Matériels Hydrauliques",
      "ar": "معدات هيدرولوجية"
    },
    "127": {
      "fr": "Autres matériels",
      "ar": "معدات أخرى"
    },
    "301": {
      "fr": "Génie Civil",
      "ar": "هندسة مدنية"
    },
    "302": {
      "fr": "Fondation Spéciale",
      "ar": "أسس خاصة"
    },
    "303": {
      "fr": "Electricité",
      "ar": "كهرباء"
    },
    "304": {
      "fr": "Equipements sanitaires",
      "ar": "مواد صحية"
    },
    "305": {
      "fr": "Climatisation",
      "ar": "تكييف"
    },
    "306": {
      "fr": "Sécurité incendie",
      "ar": "الوقاية من الحرائق"
    },
    "309": {
      "fr": "Menuiserie",
      "ar": "نجارة"
    },
    "314": {
      "fr": "Ascenseur",
      "ar": "مصعد"
    },
    "315": {
      "fr": "Terrassement",
      "ar": "تتريب"
    },
    "316": {
      "fr": "Revêtement routier",
      "ar": "تغليف طرقات"
    },
    "317": {
      "fr": "Signalisation",
      "ar": "تشوير"
    },
    "318": {
      "fr": "Ouvrage d’art",
      "ar": "منشأة فنية"
    },
    "319": {
      "fr": "VRD",
      "ar": "شبكات وطرقات مختلفة"
    },
    "320": {
      "fr": "Carrières",
      "ar": "مقطع"
    },
    "321": {
      "fr": "Pose de canalisation",
      "ar": "مد قنوات"
    },
    "322": {
      "fr": "Ouvrages hydrauliques",
      "ar": "منشأة مائية"
    },
    "325": {
      "fr": "Forages hydrauliques",
      "ar": "التنقيب المائي"
    },
    "329": {
      "fr": "Travaux de réhabilitation",
      "ar": "أشغال تهيئة"
    },
    "330": {
      "fr": "Autres travaux",
      "ar": "أشغال أخرى"
    },
    "501": {
      "fr": "Services",
      "ar": "خدمات"
    },
    "503": {
      "fr": "Maintenance",
      "ar": "صيانة"
    },
    "504": {
      "fr": "Transport",
      "ar": "نقل"
    },
    "505": {
      "fr": "Gardiennage",
      "ar": "حراسة"
    },
    "506": {
      "fr": "Nettoyage",
      "ar": "تنظيف"
    },
    "507": {
      "fr": "Autres services",
      "ar": "خدمات أخرى"
    },
    "701": {
      "fr": "Etudes",
      "ar": "دراسات"
    },
    "706": {
      "fr": "Consulting en ingénierie",
      "ar": "إستشارات هندسية"
    },
    "711": {
      "fr": "Contrôle et assistance technique",
      "ar": "المراقبة والمساعدة الفنية"
    },
    "712": {
      "fr": "Formation",
      "ar": "تكوين"
    },
    "713": {
      "fr": "Autres etudes",
      "ar": "دراسات أخرى"
    }
  },
  "procedure": {
    "1": {
      "fr": "Appel d'offres ouvert",
      "ar": "طلب عروض مفتوح"
    },
    "5": {
      "fr": "Appel d'offres avec concours",
      "ar": "طلب عروض مع مناظرة"
    }
  },
  "priceType": {
    "02": {
      "fr": "Marché à prix unitaire",
      "ar": "صفقة بأسعار فردية"
    },
    "04": {
      "fr": "Engagement sur le prix unitaire",
      "ar": "الإلتزام بالسعر الفردي"
    },
    "03": {
      "fr": "Marché à prix mixte",
      "ar": "صفقة بأسعار جزافية وفردية"
    },
    "01": {
      "fr": "Marché à prix forfaitaire",
      "ar": "صفقة بأسعار جزافية"
    }
  },
  "guarantee": {
    "1": {
      "fr": "Engagement personnel et solidaire",
      "ar": "إلتزام كفيل بالتضامن"
    },
    "2": {
      "fr": "Cautionnement",
      "ar": "الضمان البنكي"
    }
  },
  "financing": {
    "11": {
      "fr": "FADES",
      "ar": "الصندوق العربي للإنماء الإقتصادي والإجتماعي"
    },
    "12": {
      "fr": "Fonds Koweitien pour le Développement Economique Arabe",
      "ar": "الصندوق الكويتي العربي للتنمية الإقتصادية"
    },
    "13": {
      "fr": "Fonds saudien de développement",
      "ar": "الصندوق السعودي للتنمية"
    },
    "15": {
      "fr": "KFW",
      "ar": "البنك الألماني للتنمية"
    },
    "18": {
      "fr": "Union Européenne",
      "ar": "الإتحاد الأروبي"
    },
    "19": {
      "fr": "Autres",
      "ar": "أخرى"
    },
    "20": {
      "fr": "fonds propres",
      "ar": "تمويل ذاتي"
    },
    "07": {
      "fr": "Budget",
      "ar": "تمويل ذاتي"
    },
    "01": {
      "fr": "Agence Française de Développement",
      "ar": "الوكالة الفرنسية للتنمية"
    },
    "03": {
      "fr": "Banque Africaine de Développement",
      "ar": "البنك الإفريقي للتنمية"
    },
    "09": {
      "fr": "Don",
      "ar": "هبة"
    },
    "06": {
      "fr": "Banque Mondiale",
      "ar": "البنك الدولي"
    },
    "04": {
      "fr": "Banque Européenne d'Investissement",
      "ar": "البنك الأروبي للإستثمار"
    }
  },
  "evaluation": {
    "1": {
      "fr": "Moins disant",
      "ar": "الأقل عطاء"
    },
    "2": {
      "fr": "Qualité/Coût",
      "ar": "الجودة/التكلفة"
    }
  }
} as const
